// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxcfgzfznrxtbnflqxhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4Y2ZnemZ6bnJ4dGJuZmxxeGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzMTU0OTIsImV4cCI6MjA4MTg5MTQ5Mn0.8BLSN6SQ4WMypBNKmGbi1EgXidUz2HtTAjFwHaxjjlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});